name: Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: make build image_tag=${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
