name: integration-test
on:
  workflow_dispatch:
    inputs:
      connector:
        description: 'Airbyte Connector'
        required: true
      repo:
        description: 'Repo to check out code from. Defaults to the main airbyte repo. Set this when building connectors from forked repos.'
        required: false
        default: 'airbytehq/airbyte'
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false


jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Search for valid connector name format
        id: regex
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '^((connectors|bases)/)?[a-zA-Z0-9-_]+$'
          regex_flags: 'i' # required to be set for this plugin
          search_string: ${{ github.event.inputs.connector }}
      - name: Validate input workflow format
        if: steps.regex.outputs.first_match != github.event.inputs.connector
        run: echo "The connector provided has an invalid format!" && exit 1
      - name: Link comment to workflow run
        if: github.event.inputs.comment-id
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :clock2: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Checkout Airbyte
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: |
          ./tools/bin/ci_integration_test.sh ${{ github.event.inputs.connector }}
        name: test ${{ github.event.inputs.connector }}
        id: test
        env:
          ACTION_RUN_ID: ${{github.run_id}}
          # Oracle expects this variable to be set. Although usually present, this is not set by default on Github virtual runners.
          TZ: UTC
      - name: Archive test reports artifacts
        if: github.event.inputs.comment-id && !success()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            **/${{ github.event.inputs.connector }}/build/reports/tests/**/**
            **/normalization_test_output/**/dbt_output.log
            **/normalization_test_output/**/destination_output.log
            **/normalization_test_output/**/build/compiled/airbyte_utils/**
            **/normalization_test_output/**/build/run/airbyte_utils/**
            **/normalization_test_output/**/models/generated/**
      - name: Report Status
        if: github.ref == 'refs/heads/master' && always()
        run: ./tools/status/report.sh ${{ github.event.inputs.connector }} ${{github.repository}} ${{github.run_id}} ${{steps.test.outcome}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STATUS_API_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STATUS_API_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
      - name: Add Success Comment
        if: github.event.inputs.comment-id && success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :white_check_mark: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Add Failure Comment
        if: github.event.inputs.comment-id && !success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :x: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
